# Generated by Django 4.2.5 on 2023-09-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_student_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('CEN-BS', 'BS in Computer Engineering'), ('CSC-BS', 'BS in Computer Science'), ('BITCS-BT', 'BI in Game Design and Development'), ('BITCSC-BT', 'BI in Computer Science'), ('CSCC-BA', 'BA in Computer Security'), ('CSCA-BA', 'BA in Computer Science'), ('DASE-BS', 'BS in Data Analytics and Systems Engineering')], max_length=200),
        ),
    ]
